name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy the app to
        type: choice
        required: true
        options:
          - DEV
          - PROD
        default: DEV

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: touch test.txt && echo "Test content" > test.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: test.txt
  
  deploy-dev:
    name: Deploy to Dev
    needs: [build]
    if: ${{ github.event.inputs.environment == 'DEV'}}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: dl-artifact
        uses: actions/download-artifact@v4
      - name: Output
        run: cat ${{ steps.dl-artifact.outputs.download-path }}/test.txt

  deploy-prod:
    name: Deploy to Production
    needs: [build]
    if: ${{ github.event.inputs.environment == 'PROD'}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Sample deployment to PRODUCTION env'
