name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy the app to
        type: choice
        required: true
        options:
          - DEV
          - PROD
        default: DEV

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo 'Sample build'
      - name: Run unit tests
        run: echo 'Sample test'
  
  deploy-dev:
    name: Deploy to Dev
    needs: [build]
    if: ${{ github.event.inputs.environment == 'DEV'}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Sample deployment to DEVELOPMENT env'

  deploy-prod:
    name: Deploy to Production
    needs: [build]
    if: ${{ github.event.inputs.environment == 'PROD'}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Sample deployment to PRODUCTION env'
